Ce fichier contiens la config de base du serveur---
MenuTexte: 
    - [glyph]home[/glyph]Accueil
    - [glyph]signal[/glyph]Serveur
    - [glyph]shopping-cart[/glyph]Boutique
    - [glyph]envelope[/glyph]Support
    - [glyph]thumbs-up[/glyph]Voter
MenuLien: 
    - index.php
    - #
    - ?&page=boutique
    - ?&page=support
    - ?&page=voter
MenuListeDeroulante: 
    [glyph]signal[/glyph]Serveur: 
        - Ban-List
MenuListeDeroulanteLien: 
    [glyph]signal[/glyph]Serveur: 
        - ?page=banlist
